version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ml_tg

  tg_bot:
    build: TGBot/.
    container_name: "tg_bot"
    depends_on:
      - rabbitmq
    networks:
      - ml_tg

  model:
    build: ModelServer/.
    container_name: "ml_model"
    depends_on:
      - rabbitmq
    networks:
      - ml_tg
  db:
    image: postgres
    environment:
      POSTGRES_DB: ml_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1;' | psql -U admin -d ml_db -h localhost -p 5432"]
      interval: 3s
      timeout: 5s
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./ThirdPartyService/pgdata:/var/lib/postgresql/data
    networks:
      - ml_tg
      
networks:
  ml_tg: