version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ml_tg

  tg_bot:
    build: TGBot/.
    container_name: "tg_bot"
    depends_on:
      - rabbitmq
    networks:
      - ml_tg

  model:
    build: ModelServer/.
    container_name: "ml_model"
    depends_on:
      - rabbitmq
    networks:
      - ml_tg

  api_manager:
    build: api_manager/Project/.
    container_name: "api_manager"
    depends_on:
      - rabbitmq
    networks:
      - ml_tg
        
  prepare_for_db:
      image: python
      volumes:
        - ./ml_db/pgdata:/var/lib/postgresql/data
        - ./ml_db/create_missing_directories.py:/app/create_missing_directories.py
      command: ["python", "/app/create_missing_directories.py"]

  ml_db:
    image: postgres:15
    container_name: "ml_db"
    environment:
      POSTGRES_DB: ml_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1;' | psql -U admin -d ml_db -h localhost -p 5432"]
      interval: 3s
      timeout: 5s
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./ml_db/pgdata:/var/lib/postgresql/data
    networks:
      - ml_tg
  
      
networks:
  ml_tg: